// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/lookup/v1/rls_config.proto

package io.grpc.lookup.v1;

/**
 * <pre>
 * A GrpcKeyBuilder applies to a given gRPC service, name, and headers.
 * </pre>
 *
 * Protobuf type {@code grpc.lookup.v1.GrpcKeyBuilder}
 */
public  final class GrpcKeyBuilder extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.lookup.v1.GrpcKeyBuilder)
    GrpcKeyBuilderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcKeyBuilder.newBuilder() to construct.
  private GrpcKeyBuilder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcKeyBuilder() {
    names_ = java.util.Collections.emptyList();
    headers_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GrpcKeyBuilder(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              names_ = new java.util.ArrayList<Name>();
              mutable_bitField0_ |= 0x00000001;
            }
            names_.add(
                input.readMessage(Name.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              headers_ = new java.util.ArrayList<NameMatcher>();
              mutable_bitField0_ |= 0x00000002;
            }
            headers_.add(
                input.readMessage(NameMatcher.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        names_ = java.util.Collections.unmodifiableList(names_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        headers_ = java.util.Collections.unmodifiableList(headers_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GrpcKeyBuilder.class, Builder.class);
  }

  public interface NameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.lookup.v1.GrpcKeyBuilder.Name)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string service = 1;</code>
     */
    String getService();
    /**
     * <code>string service = 1;</code>
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    /**
     * <code>string method = 2;</code>
     */
    String getMethod();
    /**
     * <code>string method = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();
  }
  /**
   * <pre>
   * To match, one of the given Name fields must match; the service and method
   * fields are specified as fixed strings.  The service name is required and
   * includes the proto package name.  The method name may be omitted, in
   * which case any method on the given service is matched.
   * </pre>
   *
   * Protobuf type {@code grpc.lookup.v1.GrpcKeyBuilder.Name}
   */
  public  static final class Name extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.lookup.v1.GrpcKeyBuilder.Name)
      NameOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Name.newBuilder() to construct.
    private Name(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Name() {
      service_ = "";
      method_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Name(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              service_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Name.class, Builder.class);
    }

    public static final int SERVICE_FIELD_NUMBER = 1;
    private volatile Object service_;
    /**
     * <code>string service = 1;</code>
     */
    public String getService() {
      Object ref = service_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        service_ = s;
        return s;
      }
    }
    /**
     * <code>string service = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServiceBytes() {
      Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_FIELD_NUMBER = 2;
    private volatile Object method_;
    /**
     * <code>string method = 2;</code>
     */
    public String getMethod() {
      Object ref = method_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      Object ref = method_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getServiceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, service_);
      }
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, method_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getServiceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, service_);
      }
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, method_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Name)) {
        return super.equals(obj);
      }
      Name other = (Name) obj;

      boolean result = true;
      result = result && getService()
          .equals(other.getService());
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getService().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Name parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Name parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Name parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Name parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Name parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Name parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Name parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Name parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Name parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Name parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Name parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Name parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Name prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * To match, one of the given Name fields must match; the service and method
     * fields are specified as fixed strings.  The service name is required and
     * includes the proto package name.  The method name may be omitted, in
     * which case any method on the given service is matched.
     * </pre>
     *
     * Protobuf type {@code grpc.lookup.v1.GrpcKeyBuilder.Name}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.lookup.v1.GrpcKeyBuilder.Name)
        NameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Name.class, Builder.class);
      }

      // Construct using io.grpc.lookup.v1.GrpcKeyBuilder.Name.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        service_ = "";

        method_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor;
      }

      public Name getDefaultInstanceForType() {
        return Name.getDefaultInstance();
      }

      public Name build() {
        Name result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Name buildPartial() {
        Name result = new Name(this);
        result.service_ = service_;
        result.method_ = method_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Name) {
          return mergeFrom((Name)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Name other) {
        if (other == Name.getDefaultInstance()) return this;
        if (!other.getService().isEmpty()) {
          service_ = other.service_;
          onChanged();
        }
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Name parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Name) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object service_ = "";
      /**
       * <code>string service = 1;</code>
       */
      public String getService() {
        Object ref = service_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string service = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder setService(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder clearService() {
        
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>string service = 1;</code>
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        service_ = value;
        onChanged();
        return this;
      }

      private Object method_ = "";
      /**
       * <code>string method = 2;</code>
       */
      public String getMethod() {
        Object ref = method_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder setMethod(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 2;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.lookup.v1.GrpcKeyBuilder.Name)
    }

    // @@protoc_insertion_point(class_scope:grpc.lookup.v1.GrpcKeyBuilder.Name)
    private static final Name DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Name();
    }

    public static Name getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Name>
        PARSER = new com.google.protobuf.AbstractParser<Name>() {
      public Name parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Name(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Name> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Name> getParserForType() {
      return PARSER;
    }

    public Name getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAMES_FIELD_NUMBER = 1;
  private java.util.List<Name> names_;
  /**
   * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
   */
  public java.util.List<Name> getNamesList() {
    return names_;
  }
  /**
   * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
   */
  public java.util.List<? extends NameOrBuilder>
      getNamesOrBuilderList() {
    return names_;
  }
  /**
   * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
   */
  public int getNamesCount() {
    return names_.size();
  }
  /**
   * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
   */
  public Name getNames(int index) {
    return names_.get(index);
  }
  /**
   * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
   */
  public NameOrBuilder getNamesOrBuilder(
      int index) {
    return names_.get(index);
  }

  public static final int HEADERS_FIELD_NUMBER = 2;
  private java.util.List<NameMatcher> headers_;
  /**
   * <pre>
   * Extract keys from all listed headers.
   * For gRPC, it is an error to specify "required_match" on the NameMatcher
   * protos.
   * </pre>
   *
   * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
   */
  public java.util.List<NameMatcher> getHeadersList() {
    return headers_;
  }
  /**
   * <pre>
   * Extract keys from all listed headers.
   * For gRPC, it is an error to specify "required_match" on the NameMatcher
   * protos.
   * </pre>
   *
   * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
   */
  public java.util.List<? extends NameMatcherOrBuilder>
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <pre>
   * Extract keys from all listed headers.
   * For gRPC, it is an error to specify "required_match" on the NameMatcher
   * protos.
   * </pre>
   *
   * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
   */
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <pre>
   * Extract keys from all listed headers.
   * For gRPC, it is an error to specify "required_match" on the NameMatcher
   * protos.
   * </pre>
   *
   * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
   */
  public NameMatcher getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <pre>
   * Extract keys from all listed headers.
   * For gRPC, it is an error to specify "required_match" on the NameMatcher
   * protos.
   * </pre>
   *
   * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
   */
  public NameMatcherOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < names_.size(); i++) {
      output.writeMessage(1, names_.get(i));
    }
    for (int i = 0; i < headers_.size(); i++) {
      output.writeMessage(2, headers_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < names_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, names_.get(i));
    }
    for (int i = 0; i < headers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, headers_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GrpcKeyBuilder)) {
      return super.equals(obj);
    }
    GrpcKeyBuilder other = (GrpcKeyBuilder) obj;

    boolean result = true;
    result = result && getNamesList()
        .equals(other.getNamesList());
    result = result && getHeadersList()
        .equals(other.getHeadersList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNamesCount() > 0) {
      hash = (37 * hash) + NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getNamesList().hashCode();
    }
    if (getHeadersCount() > 0) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeadersList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GrpcKeyBuilder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrpcKeyBuilder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrpcKeyBuilder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrpcKeyBuilder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrpcKeyBuilder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GrpcKeyBuilder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GrpcKeyBuilder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrpcKeyBuilder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrpcKeyBuilder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GrpcKeyBuilder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GrpcKeyBuilder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GrpcKeyBuilder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GrpcKeyBuilder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A GrpcKeyBuilder applies to a given gRPC service, name, and headers.
   * </pre>
   *
   * Protobuf type {@code grpc.lookup.v1.GrpcKeyBuilder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.lookup.v1.GrpcKeyBuilder)
      GrpcKeyBuilderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GrpcKeyBuilder.class, Builder.class);
    }

    // Construct using io.grpc.lookup.v1.GrpcKeyBuilder.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNamesFieldBuilder();
        getHeadersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (namesBuilder_ == null) {
        names_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        namesBuilder_.clear();
      }
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        headersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor;
    }

    public GrpcKeyBuilder getDefaultInstanceForType() {
      return GrpcKeyBuilder.getDefaultInstance();
    }

    public GrpcKeyBuilder build() {
      GrpcKeyBuilder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public GrpcKeyBuilder buildPartial() {
      GrpcKeyBuilder result = new GrpcKeyBuilder(this);
      int from_bitField0_ = bitField0_;
      if (namesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          names_ = java.util.Collections.unmodifiableList(names_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.names_ = names_;
      } else {
        result.names_ = namesBuilder_.build();
      }
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.headers_ = headers_;
      } else {
        result.headers_ = headersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GrpcKeyBuilder) {
        return mergeFrom((GrpcKeyBuilder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GrpcKeyBuilder other) {
      if (other == GrpcKeyBuilder.getDefaultInstance()) return this;
      if (namesBuilder_ == null) {
        if (!other.names_.isEmpty()) {
          if (names_.isEmpty()) {
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNamesIsMutable();
            names_.addAll(other.names_);
          }
          onChanged();
        }
      } else {
        if (!other.names_.isEmpty()) {
          if (namesBuilder_.isEmpty()) {
            namesBuilder_.dispose();
            namesBuilder_ = null;
            names_ = other.names_;
            bitField0_ = (bitField0_ & ~0x00000001);
            namesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNamesFieldBuilder() : null;
          } else {
            namesBuilder_.addAllMessages(other.names_);
          }
        }
      }
      if (headersBuilder_ == null) {
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
      } else {
        if (!other.headers_.isEmpty()) {
          if (headersBuilder_.isEmpty()) {
            headersBuilder_.dispose();
            headersBuilder_ = null;
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000002);
            headersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeadersFieldBuilder() : null;
          } else {
            headersBuilder_.addAllMessages(other.headers_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GrpcKeyBuilder parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GrpcKeyBuilder) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Name> names_ =
      java.util.Collections.emptyList();
    private void ensureNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        names_ = new java.util.ArrayList<Name>(names_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Name, Name.Builder, NameOrBuilder> namesBuilder_;

    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public java.util.List<Name> getNamesList() {
      if (namesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(names_);
      } else {
        return namesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public int getNamesCount() {
      if (namesBuilder_ == null) {
        return names_.size();
      } else {
        return namesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Name getNames(int index) {
      if (namesBuilder_ == null) {
        return names_.get(index);
      } else {
        return namesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder setNames(
        int index, Name value) {
      if (namesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamesIsMutable();
        names_.set(index, value);
        onChanged();
      } else {
        namesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder setNames(
        int index, Name.Builder builderForValue) {
      if (namesBuilder_ == null) {
        ensureNamesIsMutable();
        names_.set(index, builderForValue.build());
        onChanged();
      } else {
        namesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder addNames(Name value) {
      if (namesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamesIsMutable();
        names_.add(value);
        onChanged();
      } else {
        namesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder addNames(
        int index, Name value) {
      if (namesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamesIsMutable();
        names_.add(index, value);
        onChanged();
      } else {
        namesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder addNames(
        Name.Builder builderForValue) {
      if (namesBuilder_ == null) {
        ensureNamesIsMutable();
        names_.add(builderForValue.build());
        onChanged();
      } else {
        namesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder addNames(
        int index, Name.Builder builderForValue) {
      if (namesBuilder_ == null) {
        ensureNamesIsMutable();
        names_.add(index, builderForValue.build());
        onChanged();
      } else {
        namesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder addAllNames(
        Iterable<? extends Name> values) {
      if (namesBuilder_ == null) {
        ensureNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, names_);
        onChanged();
      } else {
        namesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder clearNames() {
      if (namesBuilder_ == null) {
        names_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        namesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Builder removeNames(int index) {
      if (namesBuilder_ == null) {
        ensureNamesIsMutable();
        names_.remove(index);
        onChanged();
      } else {
        namesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Name.Builder getNamesBuilder(
        int index) {
      return getNamesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public NameOrBuilder getNamesOrBuilder(
        int index) {
      if (namesBuilder_ == null) {
        return names_.get(index);  } else {
        return namesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public java.util.List<? extends NameOrBuilder>
         getNamesOrBuilderList() {
      if (namesBuilder_ != null) {
        return namesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(names_);
      }
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Name.Builder addNamesBuilder() {
      return getNamesFieldBuilder().addBuilder(
          Name.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public Name.Builder addNamesBuilder(
        int index) {
      return getNamesFieldBuilder().addBuilder(
          index, Name.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc.lookup.v1.GrpcKeyBuilder.Name names = 1;</code>
     */
    public java.util.List<Name.Builder>
         getNamesBuilderList() {
      return getNamesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Name, Name.Builder, NameOrBuilder>
        getNamesFieldBuilder() {
      if (namesBuilder_ == null) {
        namesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Name, Name.Builder, NameOrBuilder>(
                names_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        names_ = null;
      }
      return namesBuilder_;
    }

    private java.util.List<NameMatcher> headers_ =
      java.util.Collections.emptyList();
    private void ensureHeadersIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        headers_ = new java.util.ArrayList<NameMatcher>(headers_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        NameMatcher, NameMatcher.Builder, NameMatcherOrBuilder> headersBuilder_;

    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public java.util.List<NameMatcher> getHeadersList() {
      if (headersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(headers_);
      } else {
        return headersBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public int getHeadersCount() {
      if (headersBuilder_ == null) {
        return headers_.size();
      } else {
        return headersBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public NameMatcher getHeaders(int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);
      } else {
        return headersBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder setHeaders(
        int index, NameMatcher value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
      } else {
        headersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder setHeaders(
        int index, NameMatcher.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.set(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder addHeaders(NameMatcher value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
      } else {
        headersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder addHeaders(
        int index, NameMatcher value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(index, value);
        onChanged();
      } else {
        headersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder addHeaders(
        NameMatcher.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder addHeaders(
        int index, NameMatcher.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder addAllHeaders(
        Iterable<? extends NameMatcher> values) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
      } else {
        headersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder clearHeaders() {
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        headersBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public Builder removeHeaders(int index) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.remove(index);
        onChanged();
      } else {
        headersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public NameMatcher.Builder getHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public NameMatcherOrBuilder getHeadersOrBuilder(
        int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);  } else {
        return headersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public java.util.List<? extends NameMatcherOrBuilder>
         getHeadersOrBuilderList() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(headers_);
      }
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public NameMatcher.Builder addHeadersBuilder() {
      return getHeadersFieldBuilder().addBuilder(
          NameMatcher.getDefaultInstance());
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public NameMatcher.Builder addHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().addBuilder(
          index, NameMatcher.getDefaultInstance());
    }
    /**
     * <pre>
     * Extract keys from all listed headers.
     * For gRPC, it is an error to specify "required_match" on the NameMatcher
     * protos.
     * </pre>
     *
     * <code>repeated .grpc.lookup.v1.NameMatcher headers = 2;</code>
     */
    public java.util.List<NameMatcher.Builder>
         getHeadersBuilderList() {
      return getHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        NameMatcher, NameMatcher.Builder, NameMatcherOrBuilder>
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            NameMatcher, NameMatcher.Builder, NameMatcherOrBuilder>(
                headers_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.lookup.v1.GrpcKeyBuilder)
  }

  // @@protoc_insertion_point(class_scope:grpc.lookup.v1.GrpcKeyBuilder)
  private static final GrpcKeyBuilder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GrpcKeyBuilder();
  }

  public static GrpcKeyBuilder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcKeyBuilder>
      PARSER = new com.google.protobuf.AbstractParser<GrpcKeyBuilder>() {
    public GrpcKeyBuilder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GrpcKeyBuilder(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcKeyBuilder> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GrpcKeyBuilder> getParserForType() {
    return PARSER;
  }

  public GrpcKeyBuilder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

