// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/lookup/v1/rls_config.proto

package io.grpc.lookup.v1;

/**
 * <pre>
 * Extract a key based on a given name (e.g. header name or query parameter
 * name).  The name must match one of the names listed in the "name" field.  If
 * the "required_match" field is true, one of the specified names must be
 * present for the keybuilder to match.
 * </pre>
 *
 * Protobuf type {@code grpc.lookup.v1.NameMatcher}
 */
public  final class NameMatcher extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.lookup.v1.NameMatcher)
    NameMatcherOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NameMatcher.newBuilder() to construct.
  private NameMatcher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NameMatcher() {
    key_ = "";
    names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    requiredMatch_ = false;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NameMatcher(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              names_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            names_.add(s);
            break;
          }
          case 24: {

            requiredMatch_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        names_ = names_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RlsConfigProto.internal_static_grpc_lookup_v1_NameMatcher_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RlsConfigProto.internal_static_grpc_lookup_v1_NameMatcher_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NameMatcher.class, Builder.class);
  }

  private int bitField0_;
  public static final int KEY_FIELD_NUMBER = 1;
  private volatile Object key_;
  /**
   * <pre>
   * The name that will be used in the RLS key_map to refer to this value.
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  public String getKey() {
    Object ref = key_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The name that will be used in the RLS key_map to refer to this value.
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    Object ref = key_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList names_;
  /**
   * <pre>
   * Ordered list of names (headers or query parameter names) that can supply
   * this value; the first one with a non-empty value is used.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getNamesList() {
    return names_;
  }
  /**
   * <pre>
   * Ordered list of names (headers or query parameter names) that can supply
   * this value; the first one with a non-empty value is used.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   */
  public int getNamesCount() {
    return names_.size();
  }
  /**
   * <pre>
   * Ordered list of names (headers or query parameter names) that can supply
   * this value; the first one with a non-empty value is used.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   */
  public String getNames(int index) {
    return names_.get(index);
  }
  /**
   * <pre>
   * Ordered list of names (headers or query parameter names) that can supply
   * this value; the first one with a non-empty value is used.
   * </pre>
   *
   * <code>repeated string names = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNamesBytes(int index) {
    return names_.getByteString(index);
  }

  public static final int REQUIRED_MATCH_FIELD_NUMBER = 3;
  private boolean requiredMatch_;
  /**
   * <pre>
   * If true, make this extraction required; the key builder will not match
   * if no value is found.
   * </pre>
   *
   * <code>bool required_match = 3;</code>
   */
  public boolean getRequiredMatch() {
    return requiredMatch_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
    }
    for (int i = 0; i < names_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, names_.getRaw(i));
    }
    if (requiredMatch_ != false) {
      output.writeBool(3, requiredMatch_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < names_.size(); i++) {
        dataSize += computeStringSizeNoTag(names_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNamesList().size();
    }
    if (requiredMatch_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, requiredMatch_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NameMatcher)) {
      return super.equals(obj);
    }
    NameMatcher other = (NameMatcher) obj;

    boolean result = true;
    result = result && getKey()
        .equals(other.getKey());
    result = result && getNamesList()
        .equals(other.getNamesList());
    result = result && (getRequiredMatch()
        == other.getRequiredMatch());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (getNamesCount() > 0) {
      hash = (37 * hash) + NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getNamesList().hashCode();
    }
    hash = (37 * hash) + REQUIRED_MATCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequiredMatch());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NameMatcher parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NameMatcher parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NameMatcher parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NameMatcher parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NameMatcher parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NameMatcher parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NameMatcher parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NameMatcher parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NameMatcher parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NameMatcher parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NameMatcher parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NameMatcher parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NameMatcher prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Extract a key based on a given name (e.g. header name or query parameter
   * name).  The name must match one of the names listed in the "name" field.  If
   * the "required_match" field is true, one of the specified names must be
   * present for the keybuilder to match.
   * </pre>
   *
   * Protobuf type {@code grpc.lookup.v1.NameMatcher}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.lookup.v1.NameMatcher)
      NameMatcherOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_NameMatcher_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_NameMatcher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NameMatcher.class, Builder.class);
    }

    // Construct using io.grpc.lookup.v1.NameMatcher.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      key_ = "";

      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      requiredMatch_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RlsConfigProto.internal_static_grpc_lookup_v1_NameMatcher_descriptor;
    }

    public NameMatcher getDefaultInstanceForType() {
      return NameMatcher.getDefaultInstance();
    }

    public NameMatcher build() {
      NameMatcher result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NameMatcher buildPartial() {
      NameMatcher result = new NameMatcher(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.key_ = key_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        names_ = names_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.names_ = names_;
      result.requiredMatch_ = requiredMatch_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NameMatcher) {
        return mergeFrom((NameMatcher)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NameMatcher other) {
      if (other == NameMatcher.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (!other.names_.isEmpty()) {
        if (names_.isEmpty()) {
          names_ = other.names_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureNamesIsMutable();
          names_.addAll(other.names_);
        }
        onChanged();
      }
      if (other.getRequiredMatch() != false) {
        setRequiredMatch(other.getRequiredMatch());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NameMatcher parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NameMatcher) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object key_ = "";
    /**
     * <pre>
     * The name that will be used in the RLS key_map to refer to this value.
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public String getKey() {
      Object ref = key_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The name that will be used in the RLS key_map to refer to this value.
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The name that will be used in the RLS key_map to refer to this value.
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public Builder setKey(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name that will be used in the RLS key_map to refer to this value.
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The name that will be used in the RLS key_map to refer to this value.
     * </pre>
     *
     * <code>string key = 1;</code>
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNamesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        names_ = new com.google.protobuf.LazyStringArrayList(names_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNamesList() {
      return names_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public int getNamesCount() {
      return names_.size();
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public String getNames(int index) {
      return names_.get(index);
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNamesBytes(int index) {
      return names_.getByteString(index);
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public Builder setNames(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
      names_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public Builder addNames(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNamesIsMutable();
      names_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public Builder addAllNames(
        Iterable<String> values) {
      ensureNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, names_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public Builder clearNames() {
      names_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Ordered list of names (headers or query parameter names) that can supply
     * this value; the first one with a non-empty value is used.
     * </pre>
     *
     * <code>repeated string names = 2;</code>
     */
    public Builder addNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNamesIsMutable();
      names_.add(value);
      onChanged();
      return this;
    }

    private boolean requiredMatch_ ;
    /**
     * <pre>
     * If true, make this extraction required; the key builder will not match
     * if no value is found.
     * </pre>
     *
     * <code>bool required_match = 3;</code>
     */
    public boolean getRequiredMatch() {
      return requiredMatch_;
    }
    /**
     * <pre>
     * If true, make this extraction required; the key builder will not match
     * if no value is found.
     * </pre>
     *
     * <code>bool required_match = 3;</code>
     */
    public Builder setRequiredMatch(boolean value) {
      
      requiredMatch_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If true, make this extraction required; the key builder will not match
     * if no value is found.
     * </pre>
     *
     * <code>bool required_match = 3;</code>
     */
    public Builder clearRequiredMatch() {
      
      requiredMatch_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.lookup.v1.NameMatcher)
  }

  // @@protoc_insertion_point(class_scope:grpc.lookup.v1.NameMatcher)
  private static final NameMatcher DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NameMatcher();
  }

  public static NameMatcher getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NameMatcher>
      PARSER = new com.google.protobuf.AbstractParser<NameMatcher>() {
    public NameMatcher parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NameMatcher(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NameMatcher> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NameMatcher> getParserForType() {
    return PARSER;
  }

  public NameMatcher getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

