// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/lookup/v1/rls_config.proto

package io.grpc.lookup.v1;

public final class RlsConfigProto {
  private RlsConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_lookup_v1_NameMatcher_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_lookup_v1_NameMatcher_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_lookup_v1_GrpcKeyBuilder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_lookup_v1_HttpKeyBuilder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_lookup_v1_HttpKeyBuilder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_lookup_v1_RouteLookupConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_lookup_v1_RouteLookupConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037grpc/lookup/v1/rls_config.proto\022\016grpc." +
      "lookup.v1\032\036google/protobuf/duration.prot" +
      "o\"A\n\013NameMatcher\022\013\n\003key\030\001 \001(\t\022\r\n\005names\030\002" +
      " \003(\t\022\026\n\016required_match\030\003 \001(\010\"\233\001\n\016GrpcKey" +
      "Builder\0222\n\005names\030\001 \003(\0132#.grpc.lookup.v1." +
      "GrpcKeyBuilder.Name\022,\n\007headers\030\002 \003(\0132\033.g" +
      "rpc.lookup.v1.NameMatcher\032\'\n\004Name\022\017\n\007ser" +
      "vice\030\001 \001(\t\022\016\n\006method\030\002 \001(\t\"\243\001\n\016HttpKeyBu" +
      "ilder\022\025\n\rhost_patterns\030\001 \003(\t\022\025\n\rpath_pat" +
      "terns\030\002 \003(\t\0225\n\020query_parameters\030\003 \003(\0132\033." +
      "grpc.lookup.v1.NameMatcher\022,\n\007headers\030\004 " +
      "\003(\0132\033.grpc.lookup.v1.NameMatcher\"\214\005\n\021Rou" +
      "teLookupConfig\0228\n\020http_keybuilders\030\001 \003(\013" +
      "2\036.grpc.lookup.v1.HttpKeyBuilder\0228\n\020grpc" +
      "_keybuilders\030\002 \003(\0132\036.grpc.lookup.v1.Grpc" +
      "KeyBuilder\022\026\n\016lookup_service\030\003 \001(\t\0229\n\026lo" +
      "okup_service_timeout\030\004 \001(\0132\031.google.prot" +
      "obuf.Duration\022*\n\007max_age\030\005 \001(\0132\031.google." +
      "protobuf.Duration\022,\n\tstale_age\030\006 \001(\0132\031.g" +
      "oogle.protobuf.Duration\022\030\n\020cache_size_by" +
      "tes\030\007 \001(\003\022\025\n\rvalid_targets\030\010 \003(\t\022\026\n\016defa" +
      "ult_target\030\t \001(\t\022`\n\033request_processing_s" +
      "trategy\030\n \001(\0162;.grpc.lookup.v1.RouteLook" +
      "upConfig.RequestProcessingStrategy\"\252\001\n\031R" +
      "equestProcessingStrategy\022\030\n\024STRATEGY_UNS" +
      "PECIFIED\020\000\022\'\n#SYNC_LOOKUP_DEFAULT_TARGET" +
      "_ON_ERROR\020\001\022!\n\035SYNC_LOOKUP_CLIENT_SEES_E" +
      "RROR\020\002\022\'\n#ASYNC_LOOKUP_DEFAULT_TARGET_ON" +
      "_MISS\020\003BS\n\021io.grpc.lookup.v1B\016RlsConfigP" +
      "rotoP\001Z,google.golang.org/grpc/lookup/gr" +
      "pc_lookup_v1b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DurationProto.getDescriptor(),
        }, assigner);
    internal_static_grpc_lookup_v1_NameMatcher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_lookup_v1_NameMatcher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_lookup_v1_NameMatcher_descriptor,
        new String[] { "Key", "Names", "RequiredMatch", });
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor,
        new String[] { "Names", "Headers", });
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor =
      internal_static_grpc_lookup_v1_GrpcKeyBuilder_descriptor.getNestedTypes().get(0);
    internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_lookup_v1_GrpcKeyBuilder_Name_descriptor,
        new String[] { "Service", "Method", });
    internal_static_grpc_lookup_v1_HttpKeyBuilder_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_lookup_v1_HttpKeyBuilder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_lookup_v1_HttpKeyBuilder_descriptor,
        new String[] { "HostPatterns", "PathPatterns", "QueryParameters", "Headers", });
    internal_static_grpc_lookup_v1_RouteLookupConfig_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_lookup_v1_RouteLookupConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_lookup_v1_RouteLookupConfig_descriptor,
        new String[] { "HttpKeybuilders", "GrpcKeybuilders", "LookupService", "LookupServiceTimeout", "MaxAge", "StaleAge", "CacheSizeBytes", "ValidTargets", "DefaultTarget", "RequestProcessingStrategy", });
    com.google.protobuf.DurationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
