// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/lookup/v1/rls.proto

package io.grpc.lookup.v1;

public interface RouteLookupResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.lookup.v1.RouteLookupResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Actual addressable entity to use for routing decision, using syntax
   * requested by the request target_type.
   * This field is deprecated in favor of the new "targets" field, below.
   * </pre>
   *
   * <code>string target = 1 [deprecated = true];</code>
   */
  @Deprecated String getTarget();
  /**
   * <pre>
   * Actual addressable entity to use for routing decision, using syntax
   * requested by the request target_type.
   * This field is deprecated in favor of the new "targets" field, below.
   * </pre>
   *
   * <code>string target = 1 [deprecated = true];</code>
   */
  @Deprecated com.google.protobuf.ByteString
      getTargetBytes();

  /**
   * <pre>
   * Prioritized list (best one first) of addressable entities to use
   * for routing, using syntax requested by the request target_type.
   * The targets will be tried in order until a healthy one is found.
   * If present, it should be used by proxy/gRPC client code instead of
   * "target" (which is deprecated).
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  java.util.List<String>
      getTargetsList();
  /**
   * <pre>
   * Prioritized list (best one first) of addressable entities to use
   * for routing, using syntax requested by the request target_type.
   * The targets will be tried in order until a healthy one is found.
   * If present, it should be used by proxy/gRPC client code instead of
   * "target" (which is deprecated).
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  int getTargetsCount();
  /**
   * <pre>
   * Prioritized list (best one first) of addressable entities to use
   * for routing, using syntax requested by the request target_type.
   * The targets will be tried in order until a healthy one is found.
   * If present, it should be used by proxy/gRPC client code instead of
   * "target" (which is deprecated).
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  String getTargets(int index);
  /**
   * <pre>
   * Prioritized list (best one first) of addressable entities to use
   * for routing, using syntax requested by the request target_type.
   * The targets will be tried in order until a healthy one is found.
   * If present, it should be used by proxy/gRPC client code instead of
   * "target" (which is deprecated).
   * </pre>
   *
   * <code>repeated string targets = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetsBytes(int index);

  /**
   * <pre>
   * Optional header value to pass along to AFE in the X-Google-RLS-Data header.
   * Cached with "target" and sent with all requests that match the request key.
   * Allows the RLS to pass its work product to the eventual target.
   * </pre>
   *
   * <code>string header_data = 2;</code>
   */
  String getHeaderData();
  /**
   * <pre>
   * Optional header value to pass along to AFE in the X-Google-RLS-Data header.
   * Cached with "target" and sent with all requests that match the request key.
   * Allows the RLS to pass its work product to the eventual target.
   * </pre>
   *
   * <code>string header_data = 2;</code>
   */
  com.google.protobuf.ByteString
      getHeaderDataBytes();
}
