// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/lookup/v1/rls.proto

package io.grpc.lookup.v1;

/**
 * Protobuf type {@code grpc.lookup.v1.RouteLookupRequest}
 */
public  final class RouteLookupRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.lookup.v1.RouteLookupRequest)
    RouteLookupRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RouteLookupRequest.newBuilder() to construct.
  private RouteLookupRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RouteLookupRequest() {
    server_ = "";
    path_ = "";
    targetType_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RouteLookupRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            server_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            targetType_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              keyMap_ = com.google.protobuf.MapField.newMapField(
                  KeyMapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<String, String>
            keyMap__ = input.readMessage(
                KeyMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            keyMap_.getMutableMap().put(
                keyMap__.getKey(), keyMap__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetKeyMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            RouteLookupRequest.class, Builder.class);
  }

  private int bitField0_;
  public static final int SERVER_FIELD_NUMBER = 1;
  private volatile Object server_;
  /**
   * <pre>
   * Full host name of the target server, e.g. firestore.googleapis.com.
   * Only set for gRPC requests; HTTP requests must use key_map explicitly.
   * </pre>
   *
   * <code>string server = 1;</code>
   */
  public String getServer() {
    Object ref = server_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      server_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Full host name of the target server, e.g. firestore.googleapis.com.
   * Only set for gRPC requests; HTTP requests must use key_map explicitly.
   * </pre>
   *
   * <code>string server = 1;</code>
   */
  public com.google.protobuf.ByteString
      getServerBytes() {
    Object ref = server_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      server_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATH_FIELD_NUMBER = 2;
  private volatile Object path_;
  /**
   * <pre>
   * Full path of the request, i.e. "/service/method".
   * Only set for gRPC requests; HTTP requests must use key_map explicitly.
   * </pre>
   *
   * <code>string path = 2;</code>
   */
  public String getPath() {
    Object ref = path_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Full path of the request, i.e. "/service/method".
   * Only set for gRPC requests; HTTP requests must use key_map explicitly.
   * </pre>
   *
   * <code>string path = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    Object ref = path_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_TYPE_FIELD_NUMBER = 3;
  private volatile Object targetType_;
  /**
   * <pre>
   * Target type allows the client to specify what kind of target format it
   * would like from RLS to allow it to find the regional server, e.g. "grpc".
   * </pre>
   *
   * <code>string target_type = 3;</code>
   */
  public String getTargetType() {
    Object ref = targetType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      targetType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Target type allows the client to specify what kind of target format it
   * would like from RLS to allow it to find the regional server, e.g. "grpc".
   * </pre>
   *
   * <code>string target_type = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTargetTypeBytes() {
    Object ref = targetType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      targetType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_MAP_FIELD_NUMBER = 4;
  private static final class KeyMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_KeyMapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> keyMap_;
  private com.google.protobuf.MapField<String, String>
  internalGetKeyMap() {
    if (keyMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          KeyMapDefaultEntryHolder.defaultEntry);
    }
    return keyMap_;
  }

  public int getKeyMapCount() {
    return internalGetKeyMap().getMap().size();
  }
  /**
   * <pre>
   * Map of key values extracted via key builders for the gRPC or HTTP request.
   * </pre>
   *
   * <code>map&lt;string, string&gt; key_map = 4;</code>
   */

  public boolean containsKeyMap(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetKeyMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getKeyMapMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, String> getKeyMap() {
    return getKeyMapMap();
  }
  /**
   * <pre>
   * Map of key values extracted via key builders for the gRPC or HTTP request.
   * </pre>
   *
   * <code>map&lt;string, string&gt; key_map = 4;</code>
   */

  public java.util.Map<String, String> getKeyMapMap() {
    return internalGetKeyMap().getMap();
  }
  /**
   * <pre>
   * Map of key values extracted via key builders for the gRPC or HTTP request.
   * </pre>
   *
   * <code>map&lt;string, string&gt; key_map = 4;</code>
   */

  public String getKeyMapOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetKeyMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Map of key values extracted via key builders for the gRPC or HTTP request.
   * </pre>
   *
   * <code>map&lt;string, string&gt; key_map = 4;</code>
   */

  public String getKeyMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, String> map =
        internalGetKeyMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getServerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, server_);
    }
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
    }
    if (!getTargetTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, targetType_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetKeyMap(),
        KeyMapDefaultEntryHolder.defaultEntry,
        4);
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getServerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, server_);
    }
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
    }
    if (!getTargetTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, targetType_);
    }
    for (java.util.Map.Entry<String, String> entry
         : internalGetKeyMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      keyMap__ = KeyMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, keyMap__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof RouteLookupRequest)) {
      return super.equals(obj);
    }
    RouteLookupRequest other = (RouteLookupRequest) obj;

    boolean result = true;
    result = result && getServer()
        .equals(other.getServer());
    result = result && getPath()
        .equals(other.getPath());
    result = result && getTargetType()
        .equals(other.getTargetType());
    result = result && internalGetKeyMap().equals(
        other.internalGetKeyMap());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVER_FIELD_NUMBER;
    hash = (53 * hash) + getServer().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    hash = (37 * hash) + TARGET_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTargetType().hashCode();
    if (!internalGetKeyMap().getMap().isEmpty()) {
      hash = (37 * hash) + KEY_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetKeyMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static RouteLookupRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteLookupRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteLookupRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteLookupRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteLookupRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static RouteLookupRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static RouteLookupRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RouteLookupRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static RouteLookupRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static RouteLookupRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static RouteLookupRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static RouteLookupRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(RouteLookupRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.lookup.v1.RouteLookupRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.lookup.v1.RouteLookupRequest)
      RouteLookupRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetKeyMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableKeyMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RouteLookupRequest.class, Builder.class);
    }

    // Construct using io.grpc.lookup.v1.RouteLookupRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      server_ = "";

      path_ = "";

      targetType_ = "";

      internalGetMutableKeyMap().clear();
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RlsProto.internal_static_grpc_lookup_v1_RouteLookupRequest_descriptor;
    }

    public RouteLookupRequest getDefaultInstanceForType() {
      return RouteLookupRequest.getDefaultInstance();
    }

    public RouteLookupRequest build() {
      RouteLookupRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public RouteLookupRequest buildPartial() {
      RouteLookupRequest result = new RouteLookupRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.server_ = server_;
      result.path_ = path_;
      result.targetType_ = targetType_;
      result.keyMap_ = internalGetKeyMap();
      result.keyMap_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof RouteLookupRequest) {
        return mergeFrom((RouteLookupRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(RouteLookupRequest other) {
      if (other == RouteLookupRequest.getDefaultInstance()) return this;
      if (!other.getServer().isEmpty()) {
        server_ = other.server_;
        onChanged();
      }
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (!other.getTargetType().isEmpty()) {
        targetType_ = other.targetType_;
        onChanged();
      }
      internalGetMutableKeyMap().mergeFrom(
          other.internalGetKeyMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      RouteLookupRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (RouteLookupRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object server_ = "";
    /**
     * <pre>
     * Full host name of the target server, e.g. firestore.googleapis.com.
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string server = 1;</code>
     */
    public String getServer() {
      Object ref = server_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        server_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Full host name of the target server, e.g. firestore.googleapis.com.
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string server = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      Object ref = server_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Full host name of the target server, e.g. firestore.googleapis.com.
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string server = 1;</code>
     */
    public Builder setServer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      server_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Full host name of the target server, e.g. firestore.googleapis.com.
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string server = 1;</code>
     */
    public Builder clearServer() {
      
      server_ = getDefaultInstance().getServer();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Full host name of the target server, e.g. firestore.googleapis.com.
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string server = 1;</code>
     */
    public Builder setServerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      server_ = value;
      onChanged();
      return this;
    }

    private Object path_ = "";
    /**
     * <pre>
     * Full path of the request, i.e. "/service/method".
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public String getPath() {
      Object ref = path_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Full path of the request, i.e. "/service/method".
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Full path of the request, i.e. "/service/method".
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public Builder setPath(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Full path of the request, i.e. "/service/method".
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Full path of the request, i.e. "/service/method".
     * Only set for gRPC requests; HTTP requests must use key_map explicitly.
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private Object targetType_ = "";
    /**
     * <pre>
     * Target type allows the client to specify what kind of target format it
     * would like from RLS to allow it to find the regional server, e.g. "grpc".
     * </pre>
     *
     * <code>string target_type = 3;</code>
     */
    public String getTargetType() {
      Object ref = targetType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        targetType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Target type allows the client to specify what kind of target format it
     * would like from RLS to allow it to find the regional server, e.g. "grpc".
     * </pre>
     *
     * <code>string target_type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTargetTypeBytes() {
      Object ref = targetType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        targetType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Target type allows the client to specify what kind of target format it
     * would like from RLS to allow it to find the regional server, e.g. "grpc".
     * </pre>
     *
     * <code>string target_type = 3;</code>
     */
    public Builder setTargetType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      targetType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target type allows the client to specify what kind of target format it
     * would like from RLS to allow it to find the regional server, e.g. "grpc".
     * </pre>
     *
     * <code>string target_type = 3;</code>
     */
    public Builder clearTargetType() {
      
      targetType_ = getDefaultInstance().getTargetType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Target type allows the client to specify what kind of target format it
     * would like from RLS to allow it to find the regional server, e.g. "grpc".
     * </pre>
     *
     * <code>string target_type = 3;</code>
     */
    public Builder setTargetTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      targetType_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, String> keyMap_;
    private com.google.protobuf.MapField<String, String>
    internalGetKeyMap() {
      if (keyMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            KeyMapDefaultEntryHolder.defaultEntry);
      }
      return keyMap_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableKeyMap() {
      onChanged();;
      if (keyMap_ == null) {
        keyMap_ = com.google.protobuf.MapField.newMapField(
            KeyMapDefaultEntryHolder.defaultEntry);
      }
      if (!keyMap_.isMutable()) {
        keyMap_ = keyMap_.copy();
      }
      return keyMap_;
    }

    public int getKeyMapCount() {
      return internalGetKeyMap().getMap().size();
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public boolean containsKeyMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetKeyMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getKeyMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getKeyMap() {
      return getKeyMapMap();
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public java.util.Map<String, String> getKeyMapMap() {
      return internalGetKeyMap().getMap();
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public String getKeyMapOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetKeyMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public String getKeyMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetKeyMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearKeyMap() {
      internalGetMutableKeyMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public Builder removeKeyMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableKeyMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableKeyMap() {
      return internalGetMutableKeyMap().getMutableMap();
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */
    public Builder putKeyMap(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableKeyMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Map of key values extracted via key builders for the gRPC or HTTP request.
     * </pre>
     *
     * <code>map&lt;string, string&gt; key_map = 4;</code>
     */

    public Builder putAllKeyMap(
        java.util.Map<String, String> values) {
      internalGetMutableKeyMap().getMutableMap()
          .putAll(values);
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.lookup.v1.RouteLookupRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.lookup.v1.RouteLookupRequest)
  private static final RouteLookupRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new RouteLookupRequest();
  }

  public static RouteLookupRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RouteLookupRequest>
      PARSER = new com.google.protobuf.AbstractParser<RouteLookupRequest>() {
    public RouteLookupRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RouteLookupRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RouteLookupRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<RouteLookupRequest> getParserForType() {
    return PARSER;
  }

  public RouteLookupRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

