// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/channelz/v1/channelz.proto

package io.grpc.channelz.v1;

/**
 * Protobuf type {@code grpc.channelz.v1.GetChannelResponse}
 */
public  final class GetChannelResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.channelz.v1.GetChannelResponse)
    GetChannelResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetChannelResponse.newBuilder() to construct.
  private GetChannelResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetChannelResponse() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetChannelResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Channel.Builder subBuilder = null;
            if (channel_ != null) {
              subBuilder = channel_.toBuilder();
            }
            channel_ = input.readMessage(Channel.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(channel_);
              channel_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChannelzProto.internal_static_grpc_channelz_v1_GetChannelResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChannelzProto.internal_static_grpc_channelz_v1_GetChannelResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetChannelResponse.class, Builder.class);
  }

  public static final int CHANNEL_FIELD_NUMBER = 1;
  private Channel channel_;
  /**
   * <pre>
   * The Channel that corresponds to the requested channel_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Channel channel = 1;</code>
   */
  public boolean hasChannel() {
    return channel_ != null;
  }
  /**
   * <pre>
   * The Channel that corresponds to the requested channel_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Channel channel = 1;</code>
   */
  public Channel getChannel() {
    return channel_ == null ? Channel.getDefaultInstance() : channel_;
  }
  /**
   * <pre>
   * The Channel that corresponds to the requested channel_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Channel channel = 1;</code>
   */
  public ChannelOrBuilder getChannelOrBuilder() {
    return getChannel();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (channel_ != null) {
      output.writeMessage(1, getChannel());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (channel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getChannel());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetChannelResponse)) {
      return super.equals(obj);
    }
    GetChannelResponse other = (GetChannelResponse) obj;

    boolean result = true;
    result = result && (hasChannel() == other.hasChannel());
    if (hasChannel()) {
      result = result && getChannel()
          .equals(other.getChannel());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasChannel()) {
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetChannelResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetChannelResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetChannelResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetChannelResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetChannelResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetChannelResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetChannelResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetChannelResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetChannelResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetChannelResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetChannelResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetChannelResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetChannelResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.channelz.v1.GetChannelResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.GetChannelResponse)
      GetChannelResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetChannelResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetChannelResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetChannelResponse.class, Builder.class);
    }

    // Construct using io.grpc.channelz.v1.GetChannelResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (channelBuilder_ == null) {
        channel_ = null;
      } else {
        channel_ = null;
        channelBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetChannelResponse_descriptor;
    }

    public GetChannelResponse getDefaultInstanceForType() {
      return GetChannelResponse.getDefaultInstance();
    }

    public GetChannelResponse build() {
      GetChannelResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public GetChannelResponse buildPartial() {
      GetChannelResponse result = new GetChannelResponse(this);
      if (channelBuilder_ == null) {
        result.channel_ = channel_;
      } else {
        result.channel_ = channelBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetChannelResponse) {
        return mergeFrom((GetChannelResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetChannelResponse other) {
      if (other == GetChannelResponse.getDefaultInstance()) return this;
      if (other.hasChannel()) {
        mergeChannel(other.getChannel());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GetChannelResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GetChannelResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Channel channel_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Channel, Channel.Builder, ChannelOrBuilder> channelBuilder_;
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public boolean hasChannel() {
      return channelBuilder_ != null || channel_ != null;
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Channel getChannel() {
      if (channelBuilder_ == null) {
        return channel_ == null ? Channel.getDefaultInstance() : channel_;
      } else {
        return channelBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Builder setChannel(Channel value) {
      if (channelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        channel_ = value;
        onChanged();
      } else {
        channelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Builder setChannel(
        Channel.Builder builderForValue) {
      if (channelBuilder_ == null) {
        channel_ = builderForValue.build();
        onChanged();
      } else {
        channelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Builder mergeChannel(Channel value) {
      if (channelBuilder_ == null) {
        if (channel_ != null) {
          channel_ =
            Channel.newBuilder(channel_).mergeFrom(value).buildPartial();
        } else {
          channel_ = value;
        }
        onChanged();
      } else {
        channelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Builder clearChannel() {
      if (channelBuilder_ == null) {
        channel_ = null;
        onChanged();
      } else {
        channel_ = null;
        channelBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public Channel.Builder getChannelBuilder() {
      
      onChanged();
      return getChannelFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    public ChannelOrBuilder getChannelOrBuilder() {
      if (channelBuilder_ != null) {
        return channelBuilder_.getMessageOrBuilder();
      } else {
        return channel_ == null ?
            Channel.getDefaultInstance() : channel_;
      }
    }
    /**
     * <pre>
     * The Channel that corresponds to the requested channel_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Channel channel = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Channel, Channel.Builder, ChannelOrBuilder>
        getChannelFieldBuilder() {
      if (channelBuilder_ == null) {
        channelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Channel, Channel.Builder, ChannelOrBuilder>(
                getChannel(),
                getParentForChildren(),
                isClean());
        channel_ = null;
      }
      return channelBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.GetChannelResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.channelz.v1.GetChannelResponse)
  private static final GetChannelResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetChannelResponse();
  }

  public static GetChannelResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetChannelResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetChannelResponse>() {
    public GetChannelResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetChannelResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetChannelResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetChannelResponse> getParserForType() {
    return PARSER;
  }

  public GetChannelResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

