// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/channelz/v1/channelz.proto

package io.grpc.channelz.v1;

/**
 * Protobuf type {@code grpc.channelz.v1.GetSocketResponse}
 */
public  final class GetSocketResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.channelz.v1.GetSocketResponse)
    GetSocketResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetSocketResponse.newBuilder() to construct.
  private GetSocketResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetSocketResponse() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetSocketResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Socket.Builder subBuilder = null;
            if (socket_ != null) {
              subBuilder = socket_.toBuilder();
            }
            socket_ = input.readMessage(Socket.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(socket_);
              socket_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChannelzProto.internal_static_grpc_channelz_v1_GetSocketResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChannelzProto.internal_static_grpc_channelz_v1_GetSocketResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetSocketResponse.class, Builder.class);
  }

  public static final int SOCKET_FIELD_NUMBER = 1;
  private Socket socket_;
  /**
   * <pre>
   * The Socket that corresponds to the requested socket_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Socket socket = 1;</code>
   */
  public boolean hasSocket() {
    return socket_ != null;
  }
  /**
   * <pre>
   * The Socket that corresponds to the requested socket_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Socket socket = 1;</code>
   */
  public Socket getSocket() {
    return socket_ == null ? Socket.getDefaultInstance() : socket_;
  }
  /**
   * <pre>
   * The Socket that corresponds to the requested socket_id.  This field
   * should be set.
   * </pre>
   *
   * <code>.grpc.channelz.v1.Socket socket = 1;</code>
   */
  public SocketOrBuilder getSocketOrBuilder() {
    return getSocket();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (socket_ != null) {
      output.writeMessage(1, getSocket());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (socket_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSocket());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetSocketResponse)) {
      return super.equals(obj);
    }
    GetSocketResponse other = (GetSocketResponse) obj;

    boolean result = true;
    result = result && (hasSocket() == other.hasSocket());
    if (hasSocket()) {
      result = result && getSocket()
          .equals(other.getSocket());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSocket()) {
      hash = (37 * hash) + SOCKET_FIELD_NUMBER;
      hash = (53 * hash) + getSocket().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetSocketResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSocketResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSocketResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSocketResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSocketResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetSocketResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetSocketResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetSocketResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetSocketResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetSocketResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetSocketResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetSocketResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetSocketResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.channelz.v1.GetSocketResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.GetSocketResponse)
      GetSocketResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetSocketResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetSocketResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetSocketResponse.class, Builder.class);
    }

    // Construct using io.grpc.channelz.v1.GetSocketResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (socketBuilder_ == null) {
        socket_ = null;
      } else {
        socket_ = null;
        socketBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChannelzProto.internal_static_grpc_channelz_v1_GetSocketResponse_descriptor;
    }

    public GetSocketResponse getDefaultInstanceForType() {
      return GetSocketResponse.getDefaultInstance();
    }

    public GetSocketResponse build() {
      GetSocketResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public GetSocketResponse buildPartial() {
      GetSocketResponse result = new GetSocketResponse(this);
      if (socketBuilder_ == null) {
        result.socket_ = socket_;
      } else {
        result.socket_ = socketBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetSocketResponse) {
        return mergeFrom((GetSocketResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetSocketResponse other) {
      if (other == GetSocketResponse.getDefaultInstance()) return this;
      if (other.hasSocket()) {
        mergeSocket(other.getSocket());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GetSocketResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GetSocketResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Socket socket_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Socket, Socket.Builder, SocketOrBuilder> socketBuilder_;
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public boolean hasSocket() {
      return socketBuilder_ != null || socket_ != null;
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Socket getSocket() {
      if (socketBuilder_ == null) {
        return socket_ == null ? Socket.getDefaultInstance() : socket_;
      } else {
        return socketBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Builder setSocket(Socket value) {
      if (socketBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        socket_ = value;
        onChanged();
      } else {
        socketBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Builder setSocket(
        Socket.Builder builderForValue) {
      if (socketBuilder_ == null) {
        socket_ = builderForValue.build();
        onChanged();
      } else {
        socketBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Builder mergeSocket(Socket value) {
      if (socketBuilder_ == null) {
        if (socket_ != null) {
          socket_ =
            Socket.newBuilder(socket_).mergeFrom(value).buildPartial();
        } else {
          socket_ = value;
        }
        onChanged();
      } else {
        socketBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Builder clearSocket() {
      if (socketBuilder_ == null) {
        socket_ = null;
        onChanged();
      } else {
        socket_ = null;
        socketBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public Socket.Builder getSocketBuilder() {
      
      onChanged();
      return getSocketFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    public SocketOrBuilder getSocketOrBuilder() {
      if (socketBuilder_ != null) {
        return socketBuilder_.getMessageOrBuilder();
      } else {
        return socket_ == null ?
            Socket.getDefaultInstance() : socket_;
      }
    }
    /**
     * <pre>
     * The Socket that corresponds to the requested socket_id.  This field
     * should be set.
     * </pre>
     *
     * <code>.grpc.channelz.v1.Socket socket = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Socket, Socket.Builder, SocketOrBuilder>
        getSocketFieldBuilder() {
      if (socketBuilder_ == null) {
        socketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Socket, Socket.Builder, SocketOrBuilder>(
                getSocket(),
                getParentForChildren(),
                isClean());
        socket_ = null;
      }
      return socketBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.GetSocketResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.channelz.v1.GetSocketResponse)
  private static final GetSocketResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetSocketResponse();
  }

  public static GetSocketResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetSocketResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetSocketResponse>() {
    public GetSocketResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetSocketResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetSocketResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GetSocketResponse> getParserForType() {
    return PARSER;
  }

  public GetSocketResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

