// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc/channelz/v1/channelz.proto

package io.grpc.channelz.v1;

/**
 * <pre>
 * Security represents details about how secure the socket is.
 * </pre>
 *
 * Protobuf type {@code grpc.channelz.v1.Security}
 */
public  final class Security extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.channelz.v1.Security)
    SecurityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Security.newBuilder() to construct.
  private Security(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Security() {
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Security(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            Tls.Builder subBuilder = null;
            if (modelCase_ == 1) {
              subBuilder = ((Tls) model_).toBuilder();
            }
            model_ =
                input.readMessage(Tls.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((Tls) model_);
              model_ = subBuilder.buildPartial();
            }
            modelCase_ = 1;
            break;
          }
          case 18: {
            OtherSecurity.Builder subBuilder = null;
            if (modelCase_ == 2) {
              subBuilder = ((OtherSecurity) model_).toBuilder();
            }
            model_ =
                input.readMessage(OtherSecurity.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((OtherSecurity) model_);
              model_ = subBuilder.buildPartial();
            }
            modelCase_ = 2;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChannelzProto.internal_static_grpc_channelz_v1_Security_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChannelzProto.internal_static_grpc_channelz_v1_Security_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Security.class, Builder.class);
  }

  public interface TlsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.channelz.v1.Security.Tls)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The cipher suite name in the RFC 4346 format:
     * https://tools.ietf.org/html/rfc4346#appendix-C
     * </pre>
     *
     * <code>string standard_name = 1;</code>
     */
    String getStandardName();
    /**
     * <pre>
     * The cipher suite name in the RFC 4346 format:
     * https://tools.ietf.org/html/rfc4346#appendix-C
     * </pre>
     *
     * <code>string standard_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getStandardNameBytes();

    /**
     * <pre>
     * Some other way to describe the cipher suite if
     * the RFC 4346 name is not available.
     * </pre>
     *
     * <code>string other_name = 2;</code>
     */
    String getOtherName();
    /**
     * <pre>
     * Some other way to describe the cipher suite if
     * the RFC 4346 name is not available.
     * </pre>
     *
     * <code>string other_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getOtherNameBytes();

    /**
     * <pre>
     * the certificate used by this endpoint.
     * </pre>
     *
     * <code>bytes local_certificate = 3;</code>
     */
    com.google.protobuf.ByteString getLocalCertificate();

    /**
     * <pre>
     * the certificate used by the remote endpoint.
     * </pre>
     *
     * <code>bytes remote_certificate = 4;</code>
     */
    com.google.protobuf.ByteString getRemoteCertificate();

    public Tls.CipherSuiteCase getCipherSuiteCase();
  }
  /**
   * Protobuf type {@code grpc.channelz.v1.Security.Tls}
   */
  public  static final class Tls extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.channelz.v1.Security.Tls)
      TlsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tls.newBuilder() to construct.
    private Tls(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tls() {
      localCertificate_ = com.google.protobuf.ByteString.EMPTY;
      remoteCertificate_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tls(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();
              cipherSuiteCase_ = 1;
              cipherSuite_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              cipherSuiteCase_ = 2;
              cipherSuite_ = s;
              break;
            }
            case 26: {

              localCertificate_ = input.readBytes();
              break;
            }
            case 34: {

              remoteCertificate_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_Tls_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_Tls_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tls.class, Builder.class);
    }

    private int cipherSuiteCase_ = 0;
    private Object cipherSuite_;
    public enum CipherSuiteCase
        implements com.google.protobuf.Internal.EnumLite {
      STANDARD_NAME(1),
      OTHER_NAME(2),
      CIPHERSUITE_NOT_SET(0);
      private final int value;
      private CipherSuiteCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static CipherSuiteCase valueOf(int value) {
        return forNumber(value);
      }

      public static CipherSuiteCase forNumber(int value) {
        switch (value) {
          case 1: return STANDARD_NAME;
          case 2: return OTHER_NAME;
          case 0: return CIPHERSUITE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CipherSuiteCase
    getCipherSuiteCase() {
      return CipherSuiteCase.forNumber(
          cipherSuiteCase_);
    }

    public static final int STANDARD_NAME_FIELD_NUMBER = 1;
    /**
     * <pre>
     * The cipher suite name in the RFC 4346 format:
     * https://tools.ietf.org/html/rfc4346#appendix-C
     * </pre>
     *
     * <code>string standard_name = 1;</code>
     */
    public String getStandardName() {
      Object ref = "";
      if (cipherSuiteCase_ == 1) {
        ref = cipherSuite_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (cipherSuiteCase_ == 1) {
          cipherSuite_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * The cipher suite name in the RFC 4346 format:
     * https://tools.ietf.org/html/rfc4346#appendix-C
     * </pre>
     *
     * <code>string standard_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStandardNameBytes() {
      Object ref = "";
      if (cipherSuiteCase_ == 1) {
        ref = cipherSuite_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (cipherSuiteCase_ == 1) {
          cipherSuite_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHER_NAME_FIELD_NUMBER = 2;
    /**
     * <pre>
     * Some other way to describe the cipher suite if
     * the RFC 4346 name is not available.
     * </pre>
     *
     * <code>string other_name = 2;</code>
     */
    public String getOtherName() {
      Object ref = "";
      if (cipherSuiteCase_ == 2) {
        ref = cipherSuite_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (cipherSuiteCase_ == 2) {
          cipherSuite_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Some other way to describe the cipher suite if
     * the RFC 4346 name is not available.
     * </pre>
     *
     * <code>string other_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOtherNameBytes() {
      Object ref = "";
      if (cipherSuiteCase_ == 2) {
        ref = cipherSuite_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (cipherSuiteCase_ == 2) {
          cipherSuite_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCAL_CERTIFICATE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString localCertificate_;
    /**
     * <pre>
     * the certificate used by this endpoint.
     * </pre>
     *
     * <code>bytes local_certificate = 3;</code>
     */
    public com.google.protobuf.ByteString getLocalCertificate() {
      return localCertificate_;
    }

    public static final int REMOTE_CERTIFICATE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString remoteCertificate_;
    /**
     * <pre>
     * the certificate used by the remote endpoint.
     * </pre>
     *
     * <code>bytes remote_certificate = 4;</code>
     */
    public com.google.protobuf.ByteString getRemoteCertificate() {
      return remoteCertificate_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cipherSuiteCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cipherSuite_);
      }
      if (cipherSuiteCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cipherSuite_);
      }
      if (!localCertificate_.isEmpty()) {
        output.writeBytes(3, localCertificate_);
      }
      if (!remoteCertificate_.isEmpty()) {
        output.writeBytes(4, remoteCertificate_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cipherSuiteCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cipherSuite_);
      }
      if (cipherSuiteCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cipherSuite_);
      }
      if (!localCertificate_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, localCertificate_);
      }
      if (!remoteCertificate_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, remoteCertificate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tls)) {
        return super.equals(obj);
      }
      Tls other = (Tls) obj;

      boolean result = true;
      result = result && getLocalCertificate()
          .equals(other.getLocalCertificate());
      result = result && getRemoteCertificate()
          .equals(other.getRemoteCertificate());
      result = result && getCipherSuiteCase().equals(
          other.getCipherSuiteCase());
      if (!result) return false;
      switch (cipherSuiteCase_) {
        case 1:
          result = result && getStandardName()
              .equals(other.getStandardName());
          break;
        case 2:
          result = result && getOtherName()
              .equals(other.getOtherName());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCAL_CERTIFICATE_FIELD_NUMBER;
      hash = (53 * hash) + getLocalCertificate().hashCode();
      hash = (37 * hash) + REMOTE_CERTIFICATE_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteCertificate().hashCode();
      switch (cipherSuiteCase_) {
        case 1:
          hash = (37 * hash) + STANDARD_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getStandardName().hashCode();
          break;
        case 2:
          hash = (37 * hash) + OTHER_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getOtherName().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tls parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tls parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tls parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tls parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tls parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tls parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tls parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tls parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tls parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tls parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tls parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tls parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tls prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.channelz.v1.Security.Tls}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.Security.Tls)
        TlsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_Tls_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_Tls_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tls.class, Builder.class);
      }

      // Construct using io.grpc.channelz.v1.Security.Tls.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        localCertificate_ = com.google.protobuf.ByteString.EMPTY;

        remoteCertificate_ = com.google.protobuf.ByteString.EMPTY;

        cipherSuiteCase_ = 0;
        cipherSuite_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_Tls_descriptor;
      }

      public Tls getDefaultInstanceForType() {
        return Tls.getDefaultInstance();
      }

      public Tls build() {
        Tls result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Tls buildPartial() {
        Tls result = new Tls(this);
        if (cipherSuiteCase_ == 1) {
          result.cipherSuite_ = cipherSuite_;
        }
        if (cipherSuiteCase_ == 2) {
          result.cipherSuite_ = cipherSuite_;
        }
        result.localCertificate_ = localCertificate_;
        result.remoteCertificate_ = remoteCertificate_;
        result.cipherSuiteCase_ = cipherSuiteCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tls) {
          return mergeFrom((Tls)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tls other) {
        if (other == Tls.getDefaultInstance()) return this;
        if (other.getLocalCertificate() != com.google.protobuf.ByteString.EMPTY) {
          setLocalCertificate(other.getLocalCertificate());
        }
        if (other.getRemoteCertificate() != com.google.protobuf.ByteString.EMPTY) {
          setRemoteCertificate(other.getRemoteCertificate());
        }
        switch (other.getCipherSuiteCase()) {
          case STANDARD_NAME: {
            cipherSuiteCase_ = 1;
            cipherSuite_ = other.cipherSuite_;
            onChanged();
            break;
          }
          case OTHER_NAME: {
            cipherSuiteCase_ = 2;
            cipherSuite_ = other.cipherSuite_;
            onChanged();
            break;
          }
          case CIPHERSUITE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tls parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tls) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int cipherSuiteCase_ = 0;
      private Object cipherSuite_;
      public CipherSuiteCase
          getCipherSuiteCase() {
        return CipherSuiteCase.forNumber(
            cipherSuiteCase_);
      }

      public Builder clearCipherSuite() {
        cipherSuiteCase_ = 0;
        cipherSuite_ = null;
        onChanged();
        return this;
      }


      /**
       * <pre>
       * The cipher suite name in the RFC 4346 format:
       * https://tools.ietf.org/html/rfc4346#appendix-C
       * </pre>
       *
       * <code>string standard_name = 1;</code>
       */
      public String getStandardName() {
        Object ref = "";
        if (cipherSuiteCase_ == 1) {
          ref = cipherSuite_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (cipherSuiteCase_ == 1) {
            cipherSuite_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The cipher suite name in the RFC 4346 format:
       * https://tools.ietf.org/html/rfc4346#appendix-C
       * </pre>
       *
       * <code>string standard_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStandardNameBytes() {
        Object ref = "";
        if (cipherSuiteCase_ == 1) {
          ref = cipherSuite_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (cipherSuiteCase_ == 1) {
            cipherSuite_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The cipher suite name in the RFC 4346 format:
       * https://tools.ietf.org/html/rfc4346#appendix-C
       * </pre>
       *
       * <code>string standard_name = 1;</code>
       */
      public Builder setStandardName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  cipherSuiteCase_ = 1;
        cipherSuite_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The cipher suite name in the RFC 4346 format:
       * https://tools.ietf.org/html/rfc4346#appendix-C
       * </pre>
       *
       * <code>string standard_name = 1;</code>
       */
      public Builder clearStandardName() {
        if (cipherSuiteCase_ == 1) {
          cipherSuiteCase_ = 0;
          cipherSuite_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The cipher suite name in the RFC 4346 format:
       * https://tools.ietf.org/html/rfc4346#appendix-C
       * </pre>
       *
       * <code>string standard_name = 1;</code>
       */
      public Builder setStandardNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        cipherSuiteCase_ = 1;
        cipherSuite_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Some other way to describe the cipher suite if
       * the RFC 4346 name is not available.
       * </pre>
       *
       * <code>string other_name = 2;</code>
       */
      public String getOtherName() {
        Object ref = "";
        if (cipherSuiteCase_ == 2) {
          ref = cipherSuite_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (cipherSuiteCase_ == 2) {
            cipherSuite_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Some other way to describe the cipher suite if
       * the RFC 4346 name is not available.
       * </pre>
       *
       * <code>string other_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOtherNameBytes() {
        Object ref = "";
        if (cipherSuiteCase_ == 2) {
          ref = cipherSuite_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (cipherSuiteCase_ == 2) {
            cipherSuite_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Some other way to describe the cipher suite if
       * the RFC 4346 name is not available.
       * </pre>
       *
       * <code>string other_name = 2;</code>
       */
      public Builder setOtherName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  cipherSuiteCase_ = 2;
        cipherSuite_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Some other way to describe the cipher suite if
       * the RFC 4346 name is not available.
       * </pre>
       *
       * <code>string other_name = 2;</code>
       */
      public Builder clearOtherName() {
        if (cipherSuiteCase_ == 2) {
          cipherSuiteCase_ = 0;
          cipherSuite_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Some other way to describe the cipher suite if
       * the RFC 4346 name is not available.
       * </pre>
       *
       * <code>string other_name = 2;</code>
       */
      public Builder setOtherNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        cipherSuiteCase_ = 2;
        cipherSuite_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString localCertificate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * the certificate used by this endpoint.
       * </pre>
       *
       * <code>bytes local_certificate = 3;</code>
       */
      public com.google.protobuf.ByteString getLocalCertificate() {
        return localCertificate_;
      }
      /**
       * <pre>
       * the certificate used by this endpoint.
       * </pre>
       *
       * <code>bytes local_certificate = 3;</code>
       */
      public Builder setLocalCertificate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localCertificate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the certificate used by this endpoint.
       * </pre>
       *
       * <code>bytes local_certificate = 3;</code>
       */
      public Builder clearLocalCertificate() {
        
        localCertificate_ = getDefaultInstance().getLocalCertificate();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString remoteCertificate_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * the certificate used by the remote endpoint.
       * </pre>
       *
       * <code>bytes remote_certificate = 4;</code>
       */
      public com.google.protobuf.ByteString getRemoteCertificate() {
        return remoteCertificate_;
      }
      /**
       * <pre>
       * the certificate used by the remote endpoint.
       * </pre>
       *
       * <code>bytes remote_certificate = 4;</code>
       */
      public Builder setRemoteCertificate(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        remoteCertificate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the certificate used by the remote endpoint.
       * </pre>
       *
       * <code>bytes remote_certificate = 4;</code>
       */
      public Builder clearRemoteCertificate() {
        
        remoteCertificate_ = getDefaultInstance().getRemoteCertificate();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.Security.Tls)
    }

    // @@protoc_insertion_point(class_scope:grpc.channelz.v1.Security.Tls)
    private static final Tls DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tls();
    }

    public static Tls getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tls>
        PARSER = new com.google.protobuf.AbstractParser<Tls>() {
      public Tls parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tls(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tls> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Tls> getParserForType() {
      return PARSER;
    }

    public Tls getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OtherSecurityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.channelz.v1.Security.OtherSecurity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The human readable version of the value.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    String getName();
    /**
     * <pre>
     * The human readable version of the value.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    boolean hasValue();
    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    com.google.protobuf.Any getValue();
    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getValueOrBuilder();
  }
  /**
   * Protobuf type {@code grpc.channelz.v1.Security.OtherSecurity}
   */
  public  static final class OtherSecurity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.channelz.v1.Security.OtherSecurity)
      OtherSecurityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OtherSecurity.newBuilder() to construct.
    private OtherSecurity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OtherSecurity() {
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OtherSecurity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (value_ != null) {
                subBuilder = value_.toBuilder();
              }
              value_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(value_);
                value_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_OtherSecurity_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_OtherSecurity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OtherSecurity.class, Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile Object name_;
    /**
     * <pre>
     * The human readable version of the value.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The human readable version of the value.
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any value_;
    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    public com.google.protobuf.Any getValue() {
      return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
    }
    /**
     * <pre>
     * The actual security details message.
     * </pre>
     *
     * <code>.google.protobuf.Any value = 2;</code>
     */
    public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
      return getValue();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (value_ != null) {
        output.writeMessage(2, getValue());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValue());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OtherSecurity)) {
        return super.equals(obj);
      }
      OtherSecurity other = (OtherSecurity) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OtherSecurity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtherSecurity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtherSecurity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtherSecurity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtherSecurity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtherSecurity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtherSecurity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OtherSecurity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OtherSecurity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OtherSecurity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OtherSecurity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OtherSecurity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OtherSecurity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.channelz.v1.Security.OtherSecurity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.Security.OtherSecurity)
        OtherSecurityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_OtherSecurity_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_OtherSecurity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OtherSecurity.class, Builder.class);
      }

      // Construct using io.grpc.channelz.v1.Security.OtherSecurity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        if (valueBuilder_ == null) {
          value_ = null;
        } else {
          value_ = null;
          valueBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChannelzProto.internal_static_grpc_channelz_v1_Security_OtherSecurity_descriptor;
      }

      public OtherSecurity getDefaultInstanceForType() {
        return OtherSecurity.getDefaultInstance();
      }

      public OtherSecurity build() {
        OtherSecurity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OtherSecurity buildPartial() {
        OtherSecurity result = new OtherSecurity(this);
        result.name_ = name_;
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OtherSecurity) {
          return mergeFrom((OtherSecurity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OtherSecurity other) {
        if (other == OtherSecurity.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OtherSecurity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OtherSecurity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object name_ = "";
      /**
       * <pre>
       * The human readable version of the value.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * The human readable version of the value.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The human readable version of the value.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The human readable version of the value.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The human readable version of the value.
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any value_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> valueBuilder_;
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public boolean hasValue() {
        return valueBuilder_ != null || value_ != null;
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.Any getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(
          com.google.protobuf.Any.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder mergeValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (value_ != null) {
            value_ =
              com.google.protobuf.Any.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = null;
          onChanged();
        } else {
          value_ = null;
          valueBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.Any.Builder getValueBuilder() {
        
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : value_;
        }
      }
      /**
       * <pre>
       * The actual security details message.
       * </pre>
       *
       * <code>.google.protobuf.Any value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.Security.OtherSecurity)
    }

    // @@protoc_insertion_point(class_scope:grpc.channelz.v1.Security.OtherSecurity)
    private static final OtherSecurity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OtherSecurity();
    }

    public static OtherSecurity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OtherSecurity>
        PARSER = new com.google.protobuf.AbstractParser<OtherSecurity>() {
      public OtherSecurity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OtherSecurity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OtherSecurity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OtherSecurity> getParserForType() {
      return PARSER;
    }

    public OtherSecurity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int modelCase_ = 0;
  private Object model_;
  public enum ModelCase
      implements com.google.protobuf.Internal.EnumLite {
    TLS(1),
    OTHER(2),
    MODEL_NOT_SET(0);
    private final int value;
    private ModelCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ModelCase valueOf(int value) {
      return forNumber(value);
    }

    public static ModelCase forNumber(int value) {
      switch (value) {
        case 1: return TLS;
        case 2: return OTHER;
        case 0: return MODEL_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ModelCase
  getModelCase() {
    return ModelCase.forNumber(
        modelCase_);
  }

  public static final int TLS_FIELD_NUMBER = 1;
  /**
   * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
   */
  public boolean hasTls() {
    return modelCase_ == 1;
  }
  /**
   * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
   */
  public Tls getTls() {
    if (modelCase_ == 1) {
       return (Tls) model_;
    }
    return Tls.getDefaultInstance();
  }
  /**
   * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
   */
  public TlsOrBuilder getTlsOrBuilder() {
    if (modelCase_ == 1) {
       return (Tls) model_;
    }
    return Tls.getDefaultInstance();
  }

  public static final int OTHER_FIELD_NUMBER = 2;
  /**
   * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
   */
  public boolean hasOther() {
    return modelCase_ == 2;
  }
  /**
   * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
   */
  public OtherSecurity getOther() {
    if (modelCase_ == 2) {
       return (OtherSecurity) model_;
    }
    return OtherSecurity.getDefaultInstance();
  }
  /**
   * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
   */
  public OtherSecurityOrBuilder getOtherOrBuilder() {
    if (modelCase_ == 2) {
       return (OtherSecurity) model_;
    }
    return OtherSecurity.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (modelCase_ == 1) {
      output.writeMessage(1, (Tls) model_);
    }
    if (modelCase_ == 2) {
      output.writeMessage(2, (OtherSecurity) model_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (modelCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (Tls) model_);
    }
    if (modelCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (OtherSecurity) model_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Security)) {
      return super.equals(obj);
    }
    Security other = (Security) obj;

    boolean result = true;
    result = result && getModelCase().equals(
        other.getModelCase());
    if (!result) return false;
    switch (modelCase_) {
      case 1:
        result = result && getTls()
            .equals(other.getTls());
        break;
      case 2:
        result = result && getOther()
            .equals(other.getOther());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (modelCase_) {
      case 1:
        hash = (37 * hash) + TLS_FIELD_NUMBER;
        hash = (53 * hash) + getTls().hashCode();
        break;
      case 2:
        hash = (37 * hash) + OTHER_FIELD_NUMBER;
        hash = (53 * hash) + getOther().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Security parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Security parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Security parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Security parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Security parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Security parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Security parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Security parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Security parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Security parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Security parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Security parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Security prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Security represents details about how secure the socket is.
   * </pre>
   *
   * Protobuf type {@code grpc.channelz.v1.Security}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.channelz.v1.Security)
      SecurityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Security.class, Builder.class);
    }

    // Construct using io.grpc.channelz.v1.Security.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      modelCase_ = 0;
      model_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChannelzProto.internal_static_grpc_channelz_v1_Security_descriptor;
    }

    public Security getDefaultInstanceForType() {
      return Security.getDefaultInstance();
    }

    public Security build() {
      Security result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Security buildPartial() {
      Security result = new Security(this);
      if (modelCase_ == 1) {
        if (tlsBuilder_ == null) {
          result.model_ = model_;
        } else {
          result.model_ = tlsBuilder_.build();
        }
      }
      if (modelCase_ == 2) {
        if (otherBuilder_ == null) {
          result.model_ = model_;
        } else {
          result.model_ = otherBuilder_.build();
        }
      }
      result.modelCase_ = modelCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Security) {
        return mergeFrom((Security)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Security other) {
      if (other == Security.getDefaultInstance()) return this;
      switch (other.getModelCase()) {
        case TLS: {
          mergeTls(other.getTls());
          break;
        }
        case OTHER: {
          mergeOther(other.getOther());
          break;
        }
        case MODEL_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Security parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Security) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int modelCase_ = 0;
    private Object model_;
    public ModelCase
        getModelCase() {
      return ModelCase.forNumber(
          modelCase_);
    }

    public Builder clearModel() {
      modelCase_ = 0;
      model_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        Tls, Tls.Builder, TlsOrBuilder> tlsBuilder_;
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public boolean hasTls() {
      return modelCase_ == 1;
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Tls getTls() {
      if (tlsBuilder_ == null) {
        if (modelCase_ == 1) {
          return (Tls) model_;
        }
        return Tls.getDefaultInstance();
      } else {
        if (modelCase_ == 1) {
          return tlsBuilder_.getMessage();
        }
        return Tls.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Builder setTls(Tls value) {
      if (tlsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        model_ = value;
        onChanged();
      } else {
        tlsBuilder_.setMessage(value);
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Builder setTls(
        Tls.Builder builderForValue) {
      if (tlsBuilder_ == null) {
        model_ = builderForValue.build();
        onChanged();
      } else {
        tlsBuilder_.setMessage(builderForValue.build());
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Builder mergeTls(Tls value) {
      if (tlsBuilder_ == null) {
        if (modelCase_ == 1 &&
            model_ != Tls.getDefaultInstance()) {
          model_ = Tls.newBuilder((Tls) model_)
              .mergeFrom(value).buildPartial();
        } else {
          model_ = value;
        }
        onChanged();
      } else {
        if (modelCase_ == 1) {
          tlsBuilder_.mergeFrom(value);
        }
        tlsBuilder_.setMessage(value);
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Builder clearTls() {
      if (tlsBuilder_ == null) {
        if (modelCase_ == 1) {
          modelCase_ = 0;
          model_ = null;
          onChanged();
        }
      } else {
        if (modelCase_ == 1) {
          modelCase_ = 0;
          model_ = null;
        }
        tlsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public Tls.Builder getTlsBuilder() {
      return getTlsFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    public TlsOrBuilder getTlsOrBuilder() {
      if ((modelCase_ == 1) && (tlsBuilder_ != null)) {
        return tlsBuilder_.getMessageOrBuilder();
      } else {
        if (modelCase_ == 1) {
          return (Tls) model_;
        }
        return Tls.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.channelz.v1.Security.Tls tls = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Tls, Tls.Builder, TlsOrBuilder>
        getTlsFieldBuilder() {
      if (tlsBuilder_ == null) {
        if (!(modelCase_ == 1)) {
          model_ = Tls.getDefaultInstance();
        }
        tlsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Tls, Tls.Builder, TlsOrBuilder>(
                (Tls) model_,
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      modelCase_ = 1;
      onChanged();;
      return tlsBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        OtherSecurity, OtherSecurity.Builder, OtherSecurityOrBuilder> otherBuilder_;
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public boolean hasOther() {
      return modelCase_ == 2;
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public OtherSecurity getOther() {
      if (otherBuilder_ == null) {
        if (modelCase_ == 2) {
          return (OtherSecurity) model_;
        }
        return OtherSecurity.getDefaultInstance();
      } else {
        if (modelCase_ == 2) {
          return otherBuilder_.getMessage();
        }
        return OtherSecurity.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public Builder setOther(OtherSecurity value) {
      if (otherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        model_ = value;
        onChanged();
      } else {
        otherBuilder_.setMessage(value);
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public Builder setOther(
        OtherSecurity.Builder builderForValue) {
      if (otherBuilder_ == null) {
        model_ = builderForValue.build();
        onChanged();
      } else {
        otherBuilder_.setMessage(builderForValue.build());
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public Builder mergeOther(OtherSecurity value) {
      if (otherBuilder_ == null) {
        if (modelCase_ == 2 &&
            model_ != OtherSecurity.getDefaultInstance()) {
          model_ = OtherSecurity.newBuilder((OtherSecurity) model_)
              .mergeFrom(value).buildPartial();
        } else {
          model_ = value;
        }
        onChanged();
      } else {
        if (modelCase_ == 2) {
          otherBuilder_.mergeFrom(value);
        }
        otherBuilder_.setMessage(value);
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public Builder clearOther() {
      if (otherBuilder_ == null) {
        if (modelCase_ == 2) {
          modelCase_ = 0;
          model_ = null;
          onChanged();
        }
      } else {
        if (modelCase_ == 2) {
          modelCase_ = 0;
          model_ = null;
        }
        otherBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public OtherSecurity.Builder getOtherBuilder() {
      return getOtherFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    public OtherSecurityOrBuilder getOtherOrBuilder() {
      if ((modelCase_ == 2) && (otherBuilder_ != null)) {
        return otherBuilder_.getMessageOrBuilder();
      } else {
        if (modelCase_ == 2) {
          return (OtherSecurity) model_;
        }
        return OtherSecurity.getDefaultInstance();
      }
    }
    /**
     * <code>.grpc.channelz.v1.Security.OtherSecurity other = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        OtherSecurity, OtherSecurity.Builder, OtherSecurityOrBuilder>
        getOtherFieldBuilder() {
      if (otherBuilder_ == null) {
        if (!(modelCase_ == 2)) {
          model_ = OtherSecurity.getDefaultInstance();
        }
        otherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            OtherSecurity, OtherSecurity.Builder, OtherSecurityOrBuilder>(
                (OtherSecurity) model_,
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      modelCase_ = 2;
      onChanged();;
      return otherBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.channelz.v1.Security)
  }

  // @@protoc_insertion_point(class_scope:grpc.channelz.v1.Security)
  private static final Security DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Security();
  }

  public static Security getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Security>
      PARSER = new com.google.protobuf.AbstractParser<Security>() {
    public Security parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Security(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Security> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Security> getParserForType() {
    return PARSER;
  }

  public Security getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

